[[redirects]]
  from = "/api"
  to = "$SHOPIFY_ACCESS_URL"
  status = 200
  force = true
  headers = {X-From = "Netlify" , Access-Control-Allow-Origin = "*", X-Shopify-Storefront-Access-Token = "$process.env.SHOPIFY_ACCESS_TOKEN",}